const data = {
 Matematika: [
  { nama: 'DIEGO BRANDO', score: 60, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Aryo Jati Kusumo', score: 45, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Juandito Ibrahim Gurning', score: 45, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Alysa Fiani Maritza Khanza', score: 40, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Naila Rosyada Wahyudi', score: 40, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'I Made Adinata Sanjaya', score: 35, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Fathan Pratama Putro', score: 35, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ketut Andra Nugraha Utama', score: 30, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Gabriel Fulbert Japutra', score: 30, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Khalfani Xavier Kamil Susanto', score: 30, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Vania Arsyla', score: 30, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Jeremi Harun Natanael Saragih', score: 25, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Anggi Dwi Pangestu', score: 20, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Diwa Putri Kurniawan', score: 20, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Fadli Dzaki Hidayat', score: 20, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Dhevin Desnathan', score: 20, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Arkan Avanendra', score: 10, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Qolbun Salim Khairur Rizkia', score: 10, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Keyla Adhelia Shafira', score: 5, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Bintang Rahman', score: 5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Adella Safitri', score: 0, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Fitri ayu auliyah', score: 0, avatar: 'https://avatar.iran.liara.run/public/girl' }
],

  Fisika: [
  { nama: 'Muhammad Aksan Fitriyadi', score: 52.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Sekar Ayu', score: 47.5, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'ROZAN HAQI N', score: 47.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Aqila Putri Asmarani', score: 42.5, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Keyshar Elnino Pratama', score: 40, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Jason Samuel', score: 25, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Bara Makiyya Madani', score: 22.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Raditya El Tristan', score: 20, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Muhamad Alfa Rizki', score: 7.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'SULTON AGUNG NOTO NEGORO', score: 7.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Tanzilal Akbar', score: 5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ruh Syafira Cahyaning Pawasa', score: 0, avatar: 'https://avatar.iran.liara.run/public/girl' }
],
Kimia: [
  { nama: 'Galang Dzaki Hazim', score: 32, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Calista Vania', score: 26, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Agus Ubaid', score: 24, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Arief Setiawan', score: 20, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ahmad Dhaffa', score: 14, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Akhmad fadilla baehaqi', score: 10, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Muhamad Emirsyah Amran', score: 8, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Rafael Bintang', score: 8, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Safira Rahmadani Agustina', score: 6, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Richard Samuel Alberto Manalu', score: 0, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Evannov Pratama Riadi', score: 0, avatar: 'https://avatar.iran.liara.run/public/boy' }
],

Informatika: [
  { nama: 'Fadiyah Nur Hanan', score: 57.5, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Ihsan Tajuddin Akmal', score: 53.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Afiq Khazindar Raiyan', score: 53.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Farisi Achmad Al-Banna', score: 53.38, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Arga Lana Fisyauqi', score: 49.96, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Joyce Eliana Aritonang', score: 42.75, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Abdul Harist Suryo', score: 39.21, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Puspita Lestari', score: 32.25, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'TIFFATUL KHALID YUSTAZAR', score: 21.62, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ahsan Fathur Rahman Alf', score: 21.5, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ulinihaayatil Qudsiyyah', score: 21.5, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'MUHAMMAD RIFKY', score: 21.38, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Axel Jason Wisang', score: 21.25, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Tapana Anisa Putri', score: 14.62, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Ronaldo', score: 14.54, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Restu Ihsan Maulana', score: 10.75, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Victoria Mitsu', score: 7.33, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Nadia Putri Ananda', score: 3.67, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Gyafanka Afwaraya', score: 0, avatar: 'https://avatar.iran.liara.run/public/boy' }
],
Biologi: [
  { nama: 'Silmi Riluvania Hakim', score: 56, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Anidya Safa', score: 52, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Adyaraka Huelni Putra', score: 50, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ahmad Faiz Akbar', score: 48, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Sadina Azzura', score: 44, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Naufal Fikri Dhiaurrahman', score: 34, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Haura Nazihah Afifah', score: 24, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Sayyidah Dzakiyah Al karimah', score: 22, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Cinta adhya ryfana', score: 20, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Fauza Al Ahnaf', score: 20, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Kheyla Wardhany', score: 18, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'wildan rizqi syahputra', score: 18, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Adella Safitri', score: 10, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'ANGGA DWI SENTOSO', score: 10, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Vinny Jezania Pasau', score: 10, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Addinu Fairuz Ahmad', score: 2, avatar: 'https://avatar.iran.liara.run/public/boy' }
],

Astronomi: [
  { nama: 'Farhan Syafiah Pasaribu', score: 69.33, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Khalil Azyumardi Abnel', score: 66.33, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Fauzan KA', score: 57.33, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Jupiter Arshavino Raditya Mustofa', score: 45.33, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'syavira az zahra', score: 45, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Ulqiya Alfi Anjani', score: 33, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Filka Ananta', score: 0, avatar: 'https://avatar.iran.liara.run/public/girl' }
],

Ekonomi: [
  { nama: 'Revandhika', score: 90, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ahmad Fauzan', score: 88, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Mahmud Abiddin', score: 86, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Muhammad Afif Abyan Hasya', score: 84, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Gifta Luthfi Al Kaysa', score: 84, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Muhammad Royyan', score: 84, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ester Anesia Panjaitan', score: 82, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Benjamin Joseph Lemanah', score: 80, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Shafwan Nizar Aulia', score: 80, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Bahrul Annazir', score: 76, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ifa Syarifah', score: 72, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Romilda Nafisah', score: 72, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Keisha Ameili', score: 68, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Doja Cat', score: 64, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Benhanan El-Barqie', score: 62, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'raihana k', score: 48, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Azzahra Fitriana Ahmadi', score: 46, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Hema Tadzikra Alifadita', score: 42, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Ayu Dwi Lestari', score: 38, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Hilma ramadhani', score: 34, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Luthfiah', score: 32, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'GUSTI AYU PUTU KAYLA', score: 20, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Siti Latifah Arnoldi', score: 14, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Anidya Safa', score: 0, avatar: 'https://avatar.iran.liara.run/public/girl' }
],

 Kebumian: [
  { nama: 'M.Naufal Aldandi', score: 71, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Keyla Amelia Neisha Putri', score: 59, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'ANITA LUTVIANA DEWI', score: 57, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Muh. Ali Firmansyah', score: 52, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Ahmeed Wafn', score: 45, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Nazran Rafie Aisar', score: 45, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Yusuf Okta Arkano', score: 41, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'NAJA EKA PUTRA RAFFIKY', score: 36, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'JULIANRO CHRISTOFEL SIMATUPANG', score: 35, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Muh. Furqon', score: 32, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Arik Ardiansyah', score: 31, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Faghan Putra Kurniawan', score: 29, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'moonaroh', score: 27, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'I Kadek Dicky Satya Darma', score: 25, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'khairunnisa fathiinah aguslizar', score: 23, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Abdul Aziz Al Ghifary', score: 21, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Mutiara Ananda Elsi', score: 10, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Ibnu Arsyaa Shidiq', score: 9, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Mahmud Abiddin', score: 2, avatar: 'https://avatar.iran.liara.run/public/boy' }
],

Geografi: [
  { nama: 'Adhli Rama Rafli Nugroho', score: 82, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Kayla Adma Sabitha', score: 70, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Aura Shikiri Paramitha', score: 70, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Nabila Muksitha', score: 63, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'bryan adiputra tan', score: 57, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Valenci Brilliany Gustov', score: 56, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Darlene', score: 52, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Alifah Zalfa Malika', score: 49, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Abdul Aziz Al Ghifary', score: 49, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Aurelia Beatriss', score: 48, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Ahmad Fauzan', score: 44, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Aiko Putri Valensia', score: 37, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'SIFA LUVENA TAUFIQAH PALUPI', score: 35, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'M. Syafiq Aqila', score: 33, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'DELITA ALAWIYAH', score: 31, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Fitri ayu auliyah', score: 28, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Fatimah Zidna Mahmudah', score: 26, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Elvia', score: 24, avatar: 'https://avatar.iran.liara.run/public/girl' },
  { nama: 'Saadi Aulia Hidan', score: 3, avatar: 'https://avatar.iran.liara.run/public/boy' },
  { nama: 'Eka Aulia Agustya', score: 2, avatar: 'https://avatar.iran.liara.run/public/girl' }
]
};
